ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
}

database {
  driverClassName = "org.h2.Driver"
  jdbcURL = "jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1"
  jdbcURL = ${?JDBC_URL}
  maxPoolSize = 10
}
